name: Update

on:
  [repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update repo
        run: bash repo.sh

      - name: Update README
        run: bash readme.sh

      - name: Commit
        uses: github-actions-x/commit
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
