on:
  issues:
    types: [opened, reopened, closed]

jobs:
  build:
    name: Update Issue Center
    runs-on: ubuntu-latest

    steps:
    - run: bash populate.sh ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.ISSUE_CENTER }}
        EVENT: issue-center-event
        ORG: fennecdjay
        REPO: issue-center
